### ISSUE TITLE
functional_vector is not Immutable

### ISSUE THREAD

**Issue by shiipou** [jkalias/functional_vector#18]
One of the main rule of the functional programming is to make everything immutable by default.

If you look at the screenshot, you see a basic test file that must succeed with immutable vector.
To explain, when you add something to the vector, it must return the vector with addition, but the old vector must not contain the added value(s).
Idem for deletion, filter, etc...

This make things better in logic because you didn't got any side effect when you execute a function.
Function has Immutable input and return the result.
Always in that way.

I'm really interested in immutable programmation in C++ and that can be good to find every point of this awesome type of programming in this language.

![image](https://user-images.githubusercontent.com/38187238/141196806-d174daec-41ad-4d9e-af30-65f86176618a.png)

**Comment by jkalias** [comment]
Hi, and thanks for your time and effort.

It seems to me that you are using the wrong function in this case. The signature of `insert_at` is
```c++
functional_vector& insert_at(int index, const T& element)
```
The instance is modified in place and a reference to it is returned, so that this function call can be chained with other calls for fluent apis.

If you want to enforce immutability you have to call the `inserting_at` function, whose signature is
```c++
[[nodiscard]] functional_vector inserting_at(int index, const T& element) const
```
which indeed returns a copy, and leaves the current instance intact.

I hope this clarifies the situation a bit, and you don't mind me closing the issue.

**Comment by shiipou** [comment]
Ow ok my bad, Didn't see that in the definition.
Thanks for you reply,
Issue was fixed ^^
